# Generated by Django 4.2.7 on 2024-12-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GatewaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('test', 'Test Mode'), ('live', 'Live Mode')], default='test', help_text='Select the operating mode for the payment gateway.', max_length=10)),
                ('payment_gateway', models.CharField(choices=[('payu', 'PayU'), ('razorpay', 'Razorpay')], default='razorpay', help_text='Select the payment gateway to be used.', max_length=10)),
                ('razorpay_api_key', models.CharField(blank=True, help_text='Enter Razorpay API Key.', max_length=255, null=True)),
                ('razorpay_api_secret', models.CharField(blank=True, help_text='Enter Razorpay API Secret.', max_length=255, null=True)),
                ('payu_merchant_key', models.CharField(blank=True, help_text='Enter PayU Merchant Key.', max_length=255, null=True)),
                ('payu_merchant_salt', models.CharField(blank=True, help_text='Enter PayU Merchant Salt.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Gateway Setting',
                'verbose_name_plural': 'Gateway Settings',
            },
        ),
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_withdrawal', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum amount allowed for withdrawal', max_digits=10)),
                ('minimum_deposit', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum amount allowed for deposit', max_digits=10)),
            ],
            options={
                'verbose_name': 'Payment Setting',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.CreateModel(
            name='RewardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_reward', models.FloatField(default=0.0, help_text='Reward given upon user signup', verbose_name='Signup Reward')),
                ('first_deposit_reward', models.FloatField(default=10.0, help_text='Percentage reward for the first deposit', verbose_name='First Deposit Reward Percentage')),
                ('second_deposit_reward', models.FloatField(default=7.5, help_text='Percentage reward for the second deposit', verbose_name='Second Deposit Reward Percentage')),
                ('third_deposit_reward', models.FloatField(default=5.0, help_text='Percentage reward for the third deposit', verbose_name='Third Deposit Reward Percentage')),
                ('referral_commission_level_1', models.FloatField(default=10.0, help_text='Referral commission percentage for Level 1', verbose_name='Referral Commission Level 1')),
                ('referral_commission_level_2', models.FloatField(default=7.0, help_text='Referral commission percentage for Level 2', verbose_name='Referral Commission Level 2')),
                ('referral_commission_level_3', models.FloatField(default=5.0, help_text='Referral commission percentage for Level 3', verbose_name='Referral Commission Level 3')),
                ('referral_commission_level_4', models.FloatField(default=3.0, help_text='Referral commission percentage for Level 4', verbose_name='Referral Commission Level 4')),
                ('referral_commission_level_5', models.FloatField(default=2.5, help_text='Referral commission percentage for Level 5', verbose_name='Referral Commission Level 5')),
                ('referral_commission_level_6', models.FloatField(default=2.0, help_text='Referral commission percentage for Level 6', verbose_name='Referral Commission Level 6')),
                ('referral_commission_level_7', models.FloatField(default=1.5, help_text='Referral commission percentage for Level 7', verbose_name='Referral Commission Level 7')),
            ],
            options={
                'verbose_name': 'Reward Setting',
                'verbose_name_plural': 'Reward Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(default='Spinzo', max_length=20)),
                ('icon', models.ImageField(upload_to='site_icons/', verbose_name='Site Icon')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
