# Generated by Django 4.2.7 on 2024-12-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='siteName',
            field=models.CharField(default='Spinzo', max_length=20),
        ),
    ]
