# Generated by Django 4.2.7 on 2024-12-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sitesettings_sitename'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('test', 'Test Mode'), ('live', 'Live Mode')], default='test', help_text='Select the operating mode for the payment gateway.', max_length=10)),
                ('payment_gateway', models.CharField(choices=[('payu', 'PayU'), ('razorpay', 'Razorpay')], default='razorpay', help_text='Select the payment gateway to be used.', max_length=10)),
                ('razorpay_api_key', models.CharField(blank=True, help_text='Enter Razorpay API Key.', max_length=255, null=True)),
                ('razorpay_api_secret', models.CharField(blank=True, help_text='Enter Razorpay API Secret.', max_length=255, null=True)),
                ('payu_merchant_key', models.CharField(blank=True, help_text='Enter PayU Merchant Key.', max_length=255, null=True)),
                ('payu_merchant_salt', models.CharField(blank=True, help_text='Enter PayU Merchant Salt.', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Gateway Setting',
                'verbose_name_plural': 'Gateway Settings',
            },
        ),
    ]
