# Generated by Django 4.2.7 on 2024-12-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_gatewaysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_withdrawal', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum amount allowed for withdrawal', max_digits=10)),
                ('minimum_deposit', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum amount allowed for deposit', max_digits=10)),
            ],
            options={
                'verbose_name': 'Payment Setting',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
    ]
