# Generated by Django 4.2.7 on 2024-12-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_paymentsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_reward', models.FloatField(help_text='Reward given upon user signup', verbose_name='Signup Reward')),
                ('first_deposit_reward_percentage', models.FloatField(help_text='Percentage reward for the first deposit', verbose_name='First Deposit Reward Percentage')),
                ('second_deposit_reward_percentage', models.FloatField(help_text='Percentage reward for the second deposit', verbose_name='Second Deposit Reward Percentage')),
                ('third_deposit_reward_percentage', models.FloatField(help_text='Percentage reward for the third deposit', verbose_name='Third Deposit Reward Percentage')),
                ('referral_commission_level_1', models.FloatField(help_text='Referral commission percentage for Level 1', verbose_name='Referral Commission Level 1')),
                ('referral_commission_level_2', models.FloatField(help_text='Referral commission percentage for Level 2', verbose_name='Referral Commission Level 2')),
                ('referral_commission_level_3', models.FloatField(help_text='Referral commission percentage for Level 3', verbose_name='Referral Commission Level 3')),
                ('referral_commission_level_4', models.FloatField(help_text='Referral commission percentage for Level 4', verbose_name='Referral Commission Level 4')),
                ('referral_commission_level_5', models.FloatField(help_text='Referral commission percentage for Level 5', verbose_name='Referral Commission Level 5')),
                ('referral_commission_level_6', models.FloatField(help_text='Referral commission percentage for Level 6', verbose_name='Referral Commission Level 6')),
                ('referral_commission_level_7', models.FloatField(help_text='Referral commission percentage for Level 7', verbose_name='Referral Commission Level 7')),
            ],
            options={
                'verbose_name': 'Reward Setting',
                'verbose_name_plural': 'Reward Settings',
            },
        ),
    ]
