# Generated by Django 4.2.7 on 2024-12-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rewardsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardsettings',
            name='first_deposit_reward_percentage',
        ),
        migrations.RemoveField(
            model_name='rewardsettings',
            name='second_deposit_reward_percentage',
        ),
        migrations.RemoveField(
            model_name='rewardsettings',
            name='third_deposit_reward_percentage',
        ),
        migrations.AddField(
            model_name='rewardsettings',
            name='first_deposit_reward',
            field=models.FloatField(default=10.0, help_text='Percentage reward for the first deposit', verbose_name='First Deposit Reward Percentage'),
        ),
        migrations.AddField(
            model_name='rewardsettings',
            name='second_deposit_reward',
            field=models.FloatField(default=7.5, help_text='Percentage reward for the second deposit', verbose_name='Second Deposit Reward Percentage'),
        ),
        migrations.AddField(
            model_name='rewardsettings',
            name='third_deposit_reward',
            field=models.FloatField(default=5.0, help_text='Percentage reward for the third deposit', verbose_name='Third Deposit Reward Percentage'),
        ),
        migrations.AlterField(
            model_name='rewardsettings',
            name='referral_commission_level_1',
            field=models.FloatField(default=10.0, help_text='Referral commission percentage for Level 1', verbose_name='Referral Commission Level 1'),
        ),
        migrations.AlterField(
            model_name='rewardsettings',
            name='referral_commission_level_2',
            field=models.FloatField(default=7.0, help_text='Referral commission percentage for Level 2', verbose_name='Referral Commission Level 2'),
        ),
        migrations.AlterField(
            model_name='rewardsettings',
            name='referral_commission_level_3',
            field=models.FloatField(default=5.0, help_text='Referral commission percentage for Level 3', verbose_name='Referral Commission Level 3'),
        ),
        migrations.AlterField(
            model_name='rewardsettings',
            name='referral_commission_level_4',
            field=models.FloatField(default=3.0, help_text='Referral commission percentage for Level 4', verbose_name='Referral Commission Level 4'),
        ),
        migrations.AlterField(
            model_name='rewardsettings',
            name='referral_commission_level_5',
            field=models.FloatField(default=2.5, help_text='Referral commission percentage for Level 5', verbose_name='Referral Commission Level 5'),
        ),
        migrations.AlterField(
            model_name='rewardsettings',
            name='referral_commission_level_6',
            field=models.FloatField(default=2.0, help_text='Referral commission percentage for Level 6', verbose_name='Referral Commission Level 6'),
        ),
        migrations.AlterField(
            model_name='rewardsettings',
            name='referral_commission_level_7',
            field=models.FloatField(default=1.5, help_text='Referral commission percentage for Level 7', verbose_name='Referral Commission Level 7'),
        ),
        migrations.AlterField(
            model_name='rewardsettings',
            name='signup_reward',
            field=models.FloatField(default=0.0, help_text='Reward given upon user signup', verbose_name='Signup Reward'),
        ),
    ]
